[package]
name = "abra_rocksdb"
version = "0.0.1"
authors = ["Karl Hobley <karlhobley10@gmail.com>"]

[dependencies]
rocksdb = "0.4.1"
rustc-serialize = "0.3"
maplit = "0.1.3"
byteorder = "0.5"
itertools = "0.5"

[dependencies.abra]
path = "../abra"
version = "0.0.1"
